name: core
description: Breaking Cues core package.

publish_to: 'none'

version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  args: ^2.0.0
  built_collection: ^5.1.1
  collection: ^1.16.0
  html: ^0.15.1
  http: ^1.1.2
  meta: ^1.8.0
  petitparser: ^6.0.2
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_web_socket: ^1.0.3
  uuid: ^4.3.3
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.4
