name: core
description: Breaking Cues core package.

publish_to: 'none'

version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  built_collection: ^5.1.1
  collection: ^1.16.0
  html: ^0.15.1
  http: ^0.13.5
  meta: ^1.8.0
  petitparser: ^5.1.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  test: ^1.21.4
