name: server
description: Breaking Cues server.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  core:
    path: ../core
  args: ^2.0.0
  path: ^1.8.3
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_static: ^1.1.1
  shelf_web_socket: ^1.0.3

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
