name: server
description: Breaking Cues server.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  core:
    path: ../core
  path: ^1.8.3
  shelf_static: ^1.1.1

dev_dependencies:
  http: ^1.1.2
  lints: ^3.0.0
  test: ^1.15.0
