import 'matcher.dart';

const bibleBooks = [
  // History
  ["Genesis"],
  ["Exodus"],
  ["Leviticus"],
  ["Numbers"],
  ["Deuteronomy"],
  ["Joshua"],
  ["Judges"],
  ["Ruth"],
  ["1 Samuel"],
  ["2 Samuel"],
  ["1 Kings"],
  ["2 Kings"],
  ["1 Chronicles"],
  ["2 Chronicles"],
  ["Ezra"],
  ["Neheimiah"],
  ["Esther"],
  ["Job"],
  // Wisdom
  ["Psalm", "Psalms"],
  ["Proverbs"],
  ["Ecclesiastes"],
  ["Song of Songs", "Song of Solomon"],
  // Prophets
  ["Isaiah"],
  ["Jeremiah"],
  ["Lamentations"],
  ["Ezekiel"],
  ["Daniel"],
  ["Hosea"],
  ["Joel"],
  ["Amos"],
  ["Obediah"],
  ["Jonah"],
  ["Micah"],
  ["Nahum"],
  ["Habbakuk"],
  ["Zephaniah"],
  ["Haggai"],
  ["Zechariah"],
  ["Malachi"],
  // Deuterocanonical
  // Gospels
  ["Matthew"],
  ["Mark"],
  ["Luke"],
  ["John"],
  // Acts
  ["Acts"],
  // Epistles
  ["Romans"],
  ["1 Corinthians"],
  ["2 Corinthians"],
  ["Galatians"],
  ["Ephesians"],
  ["Philippians"],
  ["Colossians"],
  ["1 Thessalonians"],
  ["2 Thessalonians"],
  ["1 Timothy"],
  ["2 Timothy"],
  ["Titus"],
  ["Philemon"],
  ["Hebrews"],
  ["James"],
  ["1 Peter"],
  ["2 Peter"],
  ["1 John"],
  ["2 John"],
  ["3 John"],
  ["Jude"],
  // Revelation
  ["Revelation"],
];

const deuterocanonicalBooks = [
  ["Tobit"],
  ["Judith"],
  ["Wisdom"],
  ["Sirach", "Ecclesiasticus"],
  ["Baruch"],
  ["Letter of Jeremiah"],
  ["Prayer of Azariah and the Song of the Three Jews"],
  ["Susanna"],
  ["Bel and the Dragon"],
  ["1 Maccabees"],
  ["2 Maccabees"],
  ["1 Esdras"],
  ["2 Esdras"],
  ["Prayer of Manasseh"],
];

final bibleBookMatcher =
    Matcher((bibleBooks + deuterocanonicalBooks).expand((x) => x));
